export const colors = {
  theme: '#F05D2A',
  themeSecondary: '#F48B5C',
  tagColor: '#FFCFBE',
  white: '#FFFFFF',
  black: '#000000',
  blackLight: '#3D3D3D',
  grey: '#D9D9D9',
  greyDark: '#9C9C9C',
  inputBg: '#EFEFEF',
  greyLight: '#CCCCCC',
  greyExtraLight: '#DADADA',
  whitish: '#F3F3F3',
  backgroundColor: '#F5F5F5',
  errorColor: '#FF0000',
}